
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-organic-s24-5pm-1
owner: ucsb-cs156-s24
repo_name: proj-organic-s24-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjE5NTA2NTY2","is_bot":false,"login":"GeorgebigG","name":"George Nebieridze"},"headRefName":"george-school-improvements","number":30,"title":"Removed TermError from the UX","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-1/pull/30"},{"author":{"id":"MDQ6VXNlcjUwMDU1NzUz","is_bot":false,"login":"rtzhang1x","name":"rt.z"},"headRefName":"rt.z-6-showSwagger","number":27,"title":"Environment Variable option to show \"Swagger\" on Navbar.","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-1/pull/27"},{"author":{"id":"MDQ6VXNlcjE5NTA2NTY2","is_bot":false,"login":"GeorgebigG","name":"George Nebieridze"},"headRefName":"staff-crud-backend-all","number":26,"title":"Added api/staff/all for the backend that lists every staff member","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-1/pull/26"},{"author":{"id":"U_kgDOBX3i4Q","is_bot":false,"login":"Peak1260","name":"Peak"},"headRefName":"Peak_StaffIndexPage","number":25,"title":"Staff Index Page","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-1/pull/25"},{"author":{"id":"U_kgDOCMuTiw","is_bot":false,"login":"ylin250","name":""},"headRefName":"dropdown-frontend","number":22,"title":"college course drop-down menu for selecting classes, instead of text input","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-1/pull/22"},{"author":{"id":"U_kgDOBX3i4Q","is_bot":false,"login":"Peak1260","name":"Peak"},"headRefName":"PM_CoursesShowPage","number":20,"title":"Course Show Page","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-1/pull/20"},{"author":{"id":"MDQ6VXNlcjE5NTA2NTY2","is_bot":false,"login":"GeorgebigG","name":"George Nebieridze"},"headRefName":"staff-crud-backend","number":15,"title":"Staff crud backend","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-1/pull/15"}]
