
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-organic-s24-5pm-1
owner: ucsb-cs156-s24
repo_name: proj-organic-s24-5pm-1
pull_requests: [{"author":{"id":"U_kgDOB3E2LA","is_bot":false,"login":"sanilkatula","name":""},"headRefName":"sk-fix","number":38,"title":"Sk fix","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-1/pull/38"},{"author":{"id":"MDQ6VXNlcjkwMTc1NDEz","is_bot":false,"login":"Crossover661","name":"Sanjay Srikanth"},"headRefName":"sanjay-dropdown2","number":37,"title":"Add default start and end dates","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-1/pull/37"},{"author":{"id":"MDQ6VXNlcjkwMTc1NDEz","is_bot":false,"login":"Crossover661","name":"Sanjay Srikanth"},"headRefName":"sanjay-dropdown","number":36,"title":"Add default start and end dates to courses form","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-1/pull/36"},{"author":{"id":"MDQ6VXNlcjE5NTA2NTY2","is_bot":false,"login":"GeorgebigG","name":"George Nebieridze"},"headRefName":"george-upload-course-roaster","number":34,"title":"Added course roster upload","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-1/pull/34"},{"author":{"id":"U_kgDOCMuTiw","is_bot":false,"login":"ylin250","name":""},"headRefName":"dropdown-frontend","number":22,"title":"college course drop-down menu for selecting classes, instead of text input","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-1/pull/22"}]
