
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-organic-s24-5pm-1
owner: ucsb-cs156-s24
repo_name: proj-organic-s24-5pm-1
pull_requests: [{"author":{"id":"U_kgDOBX3i4Q","is_bot":false,"login":"Peak1260","name":"Peak"},"headRefName":"Peak-StudentTable","number":33,"title":"Student Table Now Appears in the Course Show Page","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-1/pull/33"},{"author":{"id":"MDQ6VXNlcjE5NTA2NTY2","is_bot":false,"login":"GeorgebigG","name":"George Nebieridze"},"headRefName":"george-schoolform-explanations","number":32,"title":"Added explanations to School Form","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-1/pull/32"},{"author":{"id":"U_kgDOCMuTiw","is_bot":false,"login":"ylin250","name":""},"headRefName":"dropdown-frontend","number":22,"title":"college course drop-down menu for selecting classes, instead of text input","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-1/pull/22"}]
